version: '3'

services:
  web:
    build: 
      dockerfile: ./web/Dockerfile
    image: 127.0.0.1:5000/web:v2
    ports:
      - "8091:80"
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 5
    networks:
      - crud_backend

  db:
    build:
      dockerfile : ./db/Dockerfile
    image: 127.0.0.1:5000/db:v2
    deploy:
      placement:
        constraints:
          - node.hostname == pb-manager
    networks:
      - crud_backend

  pma:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "8151:80"
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.hostname == pb-node1
    networks:
      - crud_backend

volumes:
  db_data:

networks:
  crud_backend:
    driver: overlay
    ipam:
      config:
        - subnet: 10.0.0.0/24
