version: '3'

services:
  web:
    build: 
      dockerfile: ./web/Dockerfile
    image: 127.0.0.1:5000/web:latest
    ports:
      - "8091:80"
    depends_on:
      - db
    deploy:
      mode: global

  db:
    build: 
      dockerfile : ./db/Dockerfile
    image: 127.0.0.1:5000/db:latest
    deploy:
      placement:
        constraints:
          - node.hostname == pb-manager

  pma:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "8151:80"
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.hostname == pb-node1

volumes:
  db_data: