# Utiliser l'image de base Grafana
FROM grafana/grafana:latest

# Ouvrir le port 3000 pour accéder à l'interface web de Grafana
EXPOSE 3000

# Définir le volume pour stocker les données de Grafana
VOLUME /var/lib/grafana
